mapping user email to nickname in MessageResponseDto
Chat-Your-Way/ChatYourWay-App pull request #80
Opened 2024-05-09 20:56 UTC by Troha7

2024-05-10 05:15 UTC, LionnoiL requested changes
немає додавання поля нікнейму в LastMessageResponseDto що повинно бути по завданню.

2024-05-10 05:15 UTC, LionnoiL commented on src/main/java/com/chat/yourway/service/ChatMessageServiceImpl.java
> +
немає перевірки на exception. setSendTo в більшості випадків буде викликати ContactNotFoundException бо такого контакта як, наприклад, Topic id=4 немає.

2024-05-10 18:46 UTC, Troha7 commented
Можливо я щось не так зрозумів але наче нікнейм є в полі sentFrom 
![test1](https://github.com/Chat-Your-Way/ChatYourWay-App/assets/106109140/b7055fa6-4076-45a9-be05-ecfc8b20a779)

2024-05-10 18:52 UTC, Troha7 commented on src/main/java/com/chat/yourway/service/ChatMessageServiceImpl.java
> +
Перевірка є 
![test3](https://github.com/Chat-Your-Way/ChatYourWay-App/assets/106109140/76682458-02c5-47df-90b8-5d43abf99a92)
Всі поля обєктів DTO  валідуються та оброблюються в классі WebsocketExceptionHandler а потім виводится повідомлення про помилку від сервера

2024-05-11 08:28 UTC, LionnoiL approved these changes

2024-05-11 08:28 UTC, LionnoiL commented on src/main/java/com/chat/yourway/service/ChatMessageServiceImpl.java
> +
так. не побачив що це приватний у тебе топік.

2024-05-11 08:28 UTC, LionnoiL commented on src/main/java/com/chat/yourway/service/ChatMessageServiceImpl.java
> +        .toList();
цей використовується тільки для публічних топіків?

2024-05-11 16:25 UTC, Troha7 commented on src/main/java/com/chat/yourway/service/ChatMessageServiceImpl.java
> +        .toList();
Це для отримання історії переписки як публічних так і приватних топіків.

2024-05-11 16:27 UTC, merged

2024-05-11 16:31 UTC, LionnoiL commented on src/main/java/com/chat/yourway/service/ChatMessageServiceImpl.java
> +        .toList();
якщо і для приватних то не бачу setSentTo

2024-05-11 17:03 UTC, Troha7 commented on src/main/java/com/chat/yourway/service/ChatMessageServiceImpl.java
> +        .toList();
Дякую я це не помітив)